### ISSUE TITLE
Wrong Number Provided

### ISSUE THREAD

**Issue by manishnic** [alpha2320/covid-19.io#36]
Number provided(9910034176) for Hindustan Air Gases in faridabad is incorrect as it my number and i am not from hindustan air gases. People who need help are getting an incorrect number resulting in wastage of their precious time. Please rectify the same at the earliest

**Comment by alpha2320** [comment]
@sharmadevanshi147  @Lakshi26  Please Re-verify the contacts 

@manishnic  I am so sorry!
